window.esdocSearchIndex = [
  [
    "d3-ionic-examples/src/app/app.module.ts~appmodule",
    "class/src/app/app.module.ts~AppModule.html",
    "<span>AppModule</span> <span class=\"search-result-import-path\">d3-ionic-examples/src/app/app.module.ts</span>",
    "class"
  ],
  [
    "d3-ionic-examples/src/pages/axes/axes.ts~axespage",
    "class/src/pages/axes/axes.ts~AxesPage.html",
    "<span>AxesPage</span> <span class=\"search-result-import-path\">d3-ionic-examples/src/pages/axes/axes.ts</span>",
    "class"
  ],
  [
    "d3-ionic-examples/src/pages/basic-elements/basic-elements.ts~basicelementspage",
    "class/src/pages/basic-elements/basic-elements.ts~BasicElementsPage.html",
    "<span>BasicElementsPage</span> <span class=\"search-result-import-path\">d3-ionic-examples/src/pages/basic-elements/basic-elements.ts</span>",
    "class"
  ],
  [
    "d3-ionic-examples/src/pages/basic-shapes/basic-shapes.ts~basicshapespage",
    "class/src/pages/basic-shapes/basic-shapes.ts~BasicShapesPage.html",
    "<span>BasicShapesPage</span> <span class=\"search-result-import-path\">d3-ionic-examples/src/pages/basic-shapes/basic-shapes.ts</span>",
    "class"
  ],
  [
    "d3-ionic-examples/src/components/common-header/common-header.ts~commonheadercomponent",
    "class/src/components/common-header/common-header.ts~CommonHeaderComponent.html",
    "<span>CommonHeaderComponent</span> <span class=\"search-result-import-path\">d3-ionic-examples/src/components/common-header/common-header.ts</span>",
    "class"
  ],
  [
    "d3-ionic-examples/src/components/index.ts~components",
    "variable/index.html#static-variable-Components",
    "<span>Components</span> <span class=\"search-result-import-path\">d3-ionic-examples/src/components/index.ts</span>",
    "variable"
  ],
  [
    "d3-ionic-examples/src/components/components.module.ts~componentsmodule",
    "class/src/components/components.module.ts~ComponentsModule.html",
    "<span>ComponentsModule</span> <span class=\"search-result-import-path\">d3-ionic-examples/src/components/components.module.ts</span>",
    "class"
  ],
  [
    "d3-ionic-examples/src/pages/dynamic-svg-coord/dynamic-svg-coord.ts~dynamicsvgcoordpage",
    "class/src/pages/dynamic-svg-coord/dynamic-svg-coord.ts~DynamicSvgCoordPage.html",
    "<span>DynamicSvgCoordPage</span> <span class=\"search-result-import-path\">d3-ionic-examples/src/pages/dynamic-svg-coord/dynamic-svg-coord.ts</span>",
    "class"
  ],
  [
    "d3-ionic-examples/src/components/expandable/expandable.ts~expandablecomponent",
    "class/src/components/expandable/expandable.ts~ExpandableComponent.html",
    "<span>ExpandableComponent</span> <span class=\"search-result-import-path\">d3-ionic-examples/src/components/expandable/expandable.ts</span>",
    "class"
  ],
  [
    "d3-ionic-examples/src/components/footer-links/footer-links.ts~footerlinkscomponent",
    "class/src/components/footer-links/footer-links.ts~FooterLinksComponent.html",
    "<span>FooterLinksComponent</span> <span class=\"search-result-import-path\">d3-ionic-examples/src/components/footer-links/footer-links.ts</span>",
    "class"
  ],
  [
    "d3-ionic-examples/src/pages/group-element-d3/group-element-d3.ts~groupelementd3page",
    "class/src/pages/group-element-d3/group-element-d3.ts~GroupElementD3Page.html",
    "<span>GroupElementD3Page</span> <span class=\"search-result-import-path\">d3-ionic-examples/src/pages/group-element-d3/group-element-d3.ts</span>",
    "class"
  ],
  [
    "d3-ionic-examples/src/pages/group-element/group-element.ts~groupelementpage",
    "class/src/pages/group-element/group-element.ts~GroupElementPage.html",
    "<span>GroupElementPage</span> <span class=\"search-result-import-path\">d3-ionic-examples/src/pages/group-element/group-element.ts</span>",
    "class"
  ],
  [
    "d3-ionic-examples/src/pages/home/home.ts~homepage",
    "class/src/pages/home/home.ts~HomePage.html",
    "<span>HomePage</span> <span class=\"search-result-import-path\">d3-ionic-examples/src/pages/home/home.ts</span>",
    "class"
  ],
  [
    "d3-ionic-examples/src/pages/installation/installation.ts~installationpage",
    "class/src/pages/installation/installation.ts~InstallationPage.html",
    "<span>InstallationPage</span> <span class=\"search-result-import-path\">d3-ionic-examples/src/pages/installation/installation.ts</span>",
    "class"
  ],
  [
    "d3-ionic-examples/src/pages/index.ts~menu",
    "variable/index.html#static-variable-Menu",
    "<span>Menu</span> <span class=\"search-result-import-path\">d3-ionic-examples/src/pages/index.ts</span>",
    "variable"
  ],
  [
    "d3-ionic-examples/src/app/app.component.ts~myapp",
    "class/src/app/app.component.ts~MyApp.html",
    "<span>MyApp</span> <span class=\"search-result-import-path\">d3-ionic-examples/src/app/app.component.ts</span>",
    "class"
  ],
  [
    "d3-ionic-examples/src/pages/index.ts~pages",
    "variable/index.html#static-variable-Pages",
    "<span>Pages</span> <span class=\"search-result-import-path\">d3-ionic-examples/src/pages/index.ts</span>",
    "variable"
  ],
  [
    "d3-ionic-examples/src/pages/index.ts~pageslist",
    "variable/index.html#static-variable-PagesList",
    "<span>PagesList</span> <span class=\"search-result-import-path\">d3-ionic-examples/src/pages/index.ts</span>",
    "variable"
  ],
  [
    "d3-ionic-examples/src/pages/paths-svg/paths-svg.ts~pathssvgpage",
    "class/src/pages/paths-svg/paths-svg.ts~PathsSvgPage.html",
    "<span>PathsSvgPage</span> <span class=\"search-result-import-path\">d3-ionic-examples/src/pages/paths-svg/paths-svg.ts</span>",
    "class"
  ],
  [
    "d3-ionic-examples/src/pages/index.ts~rootpage",
    "variable/index.html#static-variable-RootPage",
    "<span>RootPage</span> <span class=\"search-result-import-path\">d3-ionic-examples/src/pages/index.ts</span>",
    "variable"
  ],
  [
    "d3-ionic-examples/src/pages/scales/scales.ts~scalespage",
    "class/src/pages/scales/scales.ts~ScalesPage.html",
    "<span>ScalesPage</span> <span class=\"search-result-import-path\">d3-ionic-examples/src/pages/scales/scales.ts</span>",
    "class"
  ],
  [
    "d3-ionic-examples/src/components/side-menu-content/side-menu-content.component.ts~sidemenucontentcomponent",
    "class/src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent.html",
    "<span>SideMenuContentComponent</span> <span class=\"search-result-import-path\">d3-ionic-examples/src/components/side-menu-content/side-menu-content.component.ts</span>",
    "class"
  ],
  [
    "d3-ionic-examples/src/components/side-menu-content/models/side-menu-redirect-events.ts~sidemenuredirectevent",
    "variable/index.html#static-variable-SideMenuRedirectEvent",
    "<span>SideMenuRedirectEvent</span> <span class=\"search-result-import-path\">d3-ionic-examples/src/components/side-menu-content/models/side-menu-redirect-events.ts</span>",
    "variable"
  ],
  [
    "d3-ionic-examples/src/pages/text-element/text-element.ts~textelementpage",
    "class/src/pages/text-element/text-element.ts~TextElementPage.html",
    "<span>TextElementPage</span> <span class=\"search-result-import-path\">d3-ionic-examples/src/pages/text-element/text-element.ts</span>",
    "class"
  ],
  [
    "src/app/app.component.ts",
    "file/src/app/app.component.ts.html",
    "src/app/app.component.ts",
    "file"
  ],
  [
    "src/app/app.component.ts~myapp#alertctrl",
    "class/src/app/app.component.ts~MyApp.html#instance-member-alertCtrl",
    "src/app/app.component.ts~MyApp#alertCtrl",
    "member"
  ],
  [
    "src/app/app.component.ts~myapp#constructor",
    "class/src/app/app.component.ts~MyApp.html#instance-constructor-constructor",
    "src/app/app.component.ts~MyApp#constructor",
    "method"
  ],
  [
    "src/app/app.component.ts~myapp#menuctrl",
    "class/src/app/app.component.ts~MyApp.html#instance-member-menuCtrl",
    "src/app/app.component.ts~MyApp#menuCtrl",
    "member"
  ],
  [
    "src/app/app.component.ts~myapp#menudata",
    "class/src/app/app.component.ts~MyApp.html#instance-member-menuData",
    "src/app/app.component.ts~MyApp#menuData",
    "member"
  ],
  [
    "src/app/app.component.ts~myapp#options",
    "class/src/app/app.component.ts~MyApp.html#instance-member-options",
    "src/app/app.component.ts~MyApp#options",
    "member"
  ],
  [
    "src/app/app.component.ts~myapp#pages",
    "class/src/app/app.component.ts~MyApp.html#instance-member-pages",
    "src/app/app.component.ts~MyApp#pages",
    "member"
  ],
  [
    "src/app/app.component.ts~myapp#rootpage",
    "class/src/app/app.component.ts~MyApp.html#instance-member-rootPage",
    "src/app/app.component.ts~MyApp#rootPage",
    "member"
  ],
  [
    "src/app/app.component.ts~myapp#selectoption",
    "class/src/app/app.component.ts~MyApp.html#instance-method-selectOption",
    "src/app/app.component.ts~MyApp#selectOption",
    "method"
  ],
  [
    "src/app/app.component.ts~myapp#sidemenusettings",
    "class/src/app/app.component.ts~MyApp.html#instance-member-sideMenuSettings",
    "src/app/app.component.ts~MyApp#sideMenuSettings",
    "member"
  ],
  [
    "src/app/app.module.ts",
    "file/src/app/app.module.ts.html",
    "src/app/app.module.ts",
    "file"
  ],
  [
    "src/app/main.ts",
    "file/src/app/main.ts.html",
    "src/app/main.ts",
    "file"
  ],
  [
    "src/components/common-header/common-header.ts",
    "file/src/components/common-header/common-header.ts.html",
    "src/components/common-header/common-header.ts",
    "file"
  ],
  [
    "src/components/common-header/common-header.ts~commonheadercomponent#constructor",
    "class/src/components/common-header/common-header.ts~CommonHeaderComponent.html#instance-constructor-constructor",
    "src/components/common-header/common-header.ts~CommonHeaderComponent#constructor",
    "method"
  ],
  [
    "src/components/common-header/common-header.ts~commonheadercomponent#defaulttitle",
    "class/src/components/common-header/common-header.ts~CommonHeaderComponent.html#instance-member-defaultTitle",
    "src/components/common-header/common-header.ts~CommonHeaderComponent#defaultTitle",
    "member"
  ],
  [
    "src/components/common-header/common-header.ts~commonheadercomponent#ngafterviewinit",
    "class/src/components/common-header/common-header.ts~CommonHeaderComponent.html#instance-method-ngAfterViewInit",
    "src/components/common-header/common-header.ts~CommonHeaderComponent#ngAfterViewInit",
    "method"
  ],
  [
    "src/components/common-header/common-header.ts~commonheadercomponent#renderer",
    "class/src/components/common-header/common-header.ts~CommonHeaderComponent.html#instance-member-renderer",
    "src/components/common-header/common-header.ts~CommonHeaderComponent#renderer",
    "member"
  ],
  [
    "src/components/components.module.ts",
    "file/src/components/components.module.ts.html",
    "src/components/components.module.ts",
    "file"
  ],
  [
    "src/components/expandable/expandable.ts",
    "file/src/components/expandable/expandable.ts.html",
    "src/components/expandable/expandable.ts",
    "file"
  ],
  [
    "src/components/expandable/expandable.ts~expandablecomponent#btncolor",
    "class/src/components/expandable/expandable.ts~ExpandableComponent.html#instance-member-btnColor",
    "src/components/expandable/expandable.ts~ExpandableComponent#btnColor",
    "member"
  ],
  [
    "src/components/expandable/expandable.ts~expandablecomponent#constructor",
    "class/src/components/expandable/expandable.ts~ExpandableComponent.html#instance-constructor-constructor",
    "src/components/expandable/expandable.ts~ExpandableComponent#constructor",
    "method"
  ],
  [
    "src/components/expandable/expandable.ts~expandablecomponent#expand",
    "class/src/components/expandable/expandable.ts~ExpandableComponent.html#instance-method-expand",
    "src/components/expandable/expandable.ts~ExpandableComponent#expand",
    "method"
  ],
  [
    "src/components/expandable/expandable.ts~expandablecomponent#expanded",
    "class/src/components/expandable/expandable.ts~ExpandableComponent.html#instance-member-expanded",
    "src/components/expandable/expandable.ts~ExpandableComponent#expanded",
    "member"
  ],
  [
    "src/components/expandable/expandable.ts~expandablecomponent#hasbutton",
    "class/src/components/expandable/expandable.ts~ExpandableComponent.html#instance-member-hasButton",
    "src/components/expandable/expandable.ts~ExpandableComponent#hasButton",
    "member"
  ],
  [
    "src/components/expandable/expandable.ts~expandablecomponent#hidebtntxt",
    "class/src/components/expandable/expandable.ts~ExpandableComponent.html#instance-member-hideBtnTxt",
    "src/components/expandable/expandable.ts~ExpandableComponent#hideBtnTxt",
    "member"
  ],
  [
    "src/components/expandable/expandable.ts~expandablecomponent#renderer",
    "class/src/components/expandable/expandable.ts~ExpandableComponent.html#instance-member-renderer",
    "src/components/expandable/expandable.ts~ExpandableComponent#renderer",
    "member"
  ],
  [
    "src/components/expandable/expandable.ts~expandablecomponent#showbtntxt",
    "class/src/components/expandable/expandable.ts~ExpandableComponent.html#instance-member-showBtnTxt",
    "src/components/expandable/expandable.ts~ExpandableComponent#showBtnTxt",
    "member"
  ],
  [
    "src/components/footer-links/footer-links.ts",
    "file/src/components/footer-links/footer-links.ts.html",
    "src/components/footer-links/footer-links.ts",
    "file"
  ],
  [
    "src/components/footer-links/footer-links.ts~footerlinkscomponent#constructor",
    "class/src/components/footer-links/footer-links.ts~FooterLinksComponent.html#instance-constructor-constructor",
    "src/components/footer-links/footer-links.ts~FooterLinksComponent#constructor",
    "method"
  ],
  [
    "src/components/footer-links/footer-links.ts~footerlinkscomponent#eventctrl",
    "class/src/components/footer-links/footer-links.ts~FooterLinksComponent.html#instance-member-eventCtrl",
    "src/components/footer-links/footer-links.ts~FooterLinksComponent#eventCtrl",
    "member"
  ],
  [
    "src/components/footer-links/footer-links.ts~footerlinkscomponent#navctrl",
    "class/src/components/footer-links/footer-links.ts~FooterLinksComponent.html#instance-member-navCtrl",
    "src/components/footer-links/footer-links.ts~FooterLinksComponent#navCtrl",
    "member"
  ],
  [
    "src/components/footer-links/footer-links.ts~footerlinkscomponent#nextpage",
    "class/src/components/footer-links/footer-links.ts~FooterLinksComponent.html#instance-member-nextPage",
    "src/components/footer-links/footer-links.ts~FooterLinksComponent#nextPage",
    "member"
  ],
  [
    "src/components/footer-links/footer-links.ts~footerlinkscomponent#ngafterviewinit",
    "class/src/components/footer-links/footer-links.ts~FooterLinksComponent.html#instance-method-ngAfterViewInit",
    "src/components/footer-links/footer-links.ts~FooterLinksComponent#ngAfterViewInit",
    "method"
  ],
  [
    "src/components/footer-links/footer-links.ts~footerlinkscomponent#openpage",
    "class/src/components/footer-links/footer-links.ts~FooterLinksComponent.html#instance-method-openPage",
    "src/components/footer-links/footer-links.ts~FooterLinksComponent#openPage",
    "method"
  ],
  [
    "src/components/footer-links/footer-links.ts~footerlinkscomponent#previouspage",
    "class/src/components/footer-links/footer-links.ts~FooterLinksComponent.html#instance-member-previousPage",
    "src/components/footer-links/footer-links.ts~FooterLinksComponent#previousPage",
    "member"
  ],
  [
    "src/components/footer-links/footer-links.ts~footerlinkscomponent#subscriptionenter",
    "class/src/components/footer-links/footer-links.ts~FooterLinksComponent.html#instance-member-subscriptionEnter",
    "src/components/footer-links/footer-links.ts~FooterLinksComponent#subscriptionEnter",
    "member"
  ],
  [
    "src/components/footer-links/footer-links.ts~footerlinkscomponent#subscriptionleave",
    "class/src/components/footer-links/footer-links.ts~FooterLinksComponent.html#instance-member-subscriptionLeave",
    "src/components/footer-links/footer-links.ts~FooterLinksComponent#subscriptionLeave",
    "member"
  ],
  [
    "src/components/index.ts",
    "file/src/components/index.ts.html",
    "src/components/index.ts",
    "file"
  ],
  [
    "src/components/side-menu-content/models/menu-option-model.ts",
    "file/src/components/side-menu-content/models/menu-option-model.ts.html",
    "src/components/side-menu-content/models/menu-option-model.ts",
    "file"
  ],
  [
    "src/components/side-menu-content/models/side-menu-redirect-events.ts",
    "file/src/components/side-menu-content/models/side-menu-redirect-events.ts.html",
    "src/components/side-menu-content/models/side-menu-redirect-events.ts",
    "file"
  ],
  [
    "src/components/side-menu-content/models/side-menu-settings.ts",
    "file/src/components/side-menu-content/models/side-menu-settings.ts.html",
    "src/components/side-menu-content/models/side-menu-settings.ts",
    "file"
  ],
  [
    "src/components/side-menu-content/side-menu-content.component.ts",
    "file/src/components/side-menu-content/side-menu-content.component.ts.html",
    "src/components/side-menu-content/side-menu-content.component.ts",
    "file"
  ],
  [
    "src/components/side-menu-content/side-menu-content.component.ts~sidemenucontentcomponent#cdref",
    "class/src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent.html#instance-member-cdRef",
    "src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent#cdRef",
    "member"
  ],
  [
    "src/components/side-menu-content/side-menu-content.component.ts~sidemenucontentcomponent#collapsableitems",
    "class/src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent.html#instance-member-collapsableItems",
    "src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent#collapsableItems",
    "member"
  ],
  [
    "src/components/side-menu-content/side-menu-content.component.ts~sidemenucontentcomponent#collapsealloptions",
    "class/src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent.html#instance-method-collapseAllOptions",
    "src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent#collapseAllOptions",
    "method"
  ],
  [
    "src/components/side-menu-content/side-menu-content.component.ts~sidemenucontentcomponent#constructor",
    "class/src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent.html#instance-constructor-constructor",
    "src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent#constructor",
    "method"
  ],
  [
    "src/components/side-menu-content/side-menu-content.component.ts~sidemenucontentcomponent#eventsctrl",
    "class/src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent.html#instance-member-eventsCtrl",
    "src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent#eventsCtrl",
    "member"
  ],
  [
    "src/components/side-menu-content/side-menu-content.component.ts~sidemenucontentcomponent#isdefined",
    "class/src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent.html#instance-method-isDefined",
    "src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent#isDefined",
    "method"
  ],
  [
    "src/components/side-menu-content/side-menu-content.component.ts~sidemenucontentcomponent#isdefinedandpositive",
    "class/src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent.html#instance-method-isDefinedAndPositive",
    "src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent#isDefinedAndPositive",
    "method"
  ],
  [
    "src/components/side-menu-content/side-menu-content.component.ts~sidemenucontentcomponent#itemheight",
    "class/src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent.html#instance-get-itemHeight",
    "src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent#itemHeight",
    "member"
  ],
  [
    "src/components/side-menu-content/side-menu-content.component.ts~sidemenucontentcomponent#menuoptions",
    "class/src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent.html#instance-member-menuOptions",
    "src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent#menuOptions",
    "member"
  ],
  [
    "src/components/side-menu-content/side-menu-content.component.ts~sidemenucontentcomponent#menusettings",
    "class/src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent.html#instance-member-menuSettings",
    "src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent#menuSettings",
    "member"
  ],
  [
    "src/components/side-menu-content/side-menu-content.component.ts~sidemenucontentcomponent#mergesettings",
    "class/src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent.html#instance-method-mergeSettings",
    "src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent#mergeSettings",
    "method"
  ],
  [
    "src/components/side-menu-content/side-menu-content.component.ts~sidemenucontentcomponent#ngondestroy",
    "class/src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent.html#instance-method-ngOnDestroy",
    "src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent#ngOnDestroy",
    "method"
  ],
  [
    "src/components/side-menu-content/side-menu-content.component.ts~sidemenucontentcomponent#options",
    "class/src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent.html#instance-set-options",
    "src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent#options",
    "member"
  ],
  [
    "src/components/side-menu-content/side-menu-content.component.ts~sidemenucontentcomponent#platform",
    "class/src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent.html#instance-member-platform",
    "src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent#platform",
    "member"
  ],
  [
    "src/components/side-menu-content/side-menu-content.component.ts~sidemenucontentcomponent#select",
    "class/src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent.html#instance-method-select",
    "src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent#select",
    "method"
  ],
  [
    "src/components/side-menu-content/side-menu-content.component.ts~sidemenucontentcomponent#selectoption",
    "class/src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent.html#instance-member-selectOption",
    "src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent#selectOption",
    "member"
  ],
  [
    "src/components/side-menu-content/side-menu-content.component.ts~sidemenucontentcomponent#selectedoption",
    "class/src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent.html#instance-member-selectedOption",
    "src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent#selectedOption",
    "member"
  ],
  [
    "src/components/side-menu-content/side-menu-content.component.ts~sidemenucontentcomponent#setselectedoption",
    "class/src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent.html#instance-method-setSelectedOption",
    "src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent#setSelectedOption",
    "method"
  ],
  [
    "src/components/side-menu-content/side-menu-content.component.ts~sidemenucontentcomponent#settings",
    "class/src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent.html#instance-set-settings",
    "src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent#settings",
    "member"
  ],
  [
    "src/components/side-menu-content/side-menu-content.component.ts~sidemenucontentcomponent#suboptionindentation",
    "class/src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent.html#instance-get-subOptionIndentation",
    "src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent#subOptionIndentation",
    "member"
  ],
  [
    "src/components/side-menu-content/side-menu-content.component.ts~sidemenucontentcomponent#toggleitemoptions",
    "class/src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent.html#instance-method-toggleItemOptions",
    "src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent#toggleItemOptions",
    "method"
  ],
  [
    "src/components/side-menu-content/side-menu-content.component.ts~sidemenucontentcomponent#updateselectedoption",
    "class/src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent.html#instance-method-updateSelectedOption",
    "src/components/side-menu-content/side-menu-content.component.ts~SideMenuContentComponent#updateSelectedOption",
    "method"
  ],
  [
    "src/pages/axes/axes.ts",
    "file/src/pages/axes/axes.ts.html",
    "src/pages/axes/axes.ts",
    "file"
  ],
  [
    "src/pages/axes/axes.ts~axespage#constructor",
    "class/src/pages/axes/axes.ts~AxesPage.html#instance-constructor-constructor",
    "src/pages/axes/axes.ts~AxesPage#constructor",
    "method"
  ],
  [
    "src/pages/axes/axes.ts~axespage#createaxis",
    "class/src/pages/axes/axes.ts~AxesPage.html#instance-method-createAxis",
    "src/pages/axes/axes.ts~AxesPage#createAxis",
    "method"
  ],
  [
    "src/pages/axes/axes.ts~axespage#createotheraxis",
    "class/src/pages/axes/axes.ts~AxesPage.html#instance-method-createOtherAxis",
    "src/pages/axes/axes.ts~AxesPage#createOtherAxis",
    "method"
  ],
  [
    "src/pages/axes/axes.ts~axespage#createsvg",
    "class/src/pages/axes/axes.ts~AxesPage.html#instance-method-createSVG",
    "src/pages/axes/axes.ts~AxesPage#createSVG",
    "method"
  ],
  [
    "src/pages/axes/axes.ts~axespage#elementref",
    "class/src/pages/axes/axes.ts~AxesPage.html#instance-member-elementRef",
    "src/pages/axes/axes.ts~AxesPage#elementRef",
    "member"
  ],
  [
    "src/pages/axes/axes.ts~axespage#ionviewdidload",
    "class/src/pages/axes/axes.ts~AxesPage.html#instance-method-ionViewDidLoad",
    "src/pages/axes/axes.ts~AxesPage#ionViewDidLoad",
    "method"
  ],
  [
    "src/pages/axes/axes.ts~axespage#navctrl",
    "class/src/pages/axes/axes.ts~AxesPage.html#instance-member-navCtrl",
    "src/pages/axes/axes.ts~AxesPage#navCtrl",
    "member"
  ],
  [
    "src/pages/axes/axes.ts~axespage#scalepage",
    "class/src/pages/axes/axes.ts~AxesPage.html#instance-member-scalePage",
    "src/pages/axes/axes.ts~AxesPage#scalePage",
    "member"
  ],
  [
    "src/pages/axes/axes.ts~axespage#xaxis",
    "class/src/pages/axes/axes.ts~AxesPage.html#instance-member-xAxis",
    "src/pages/axes/axes.ts~AxesPage#xAxis",
    "member"
  ],
  [
    "src/pages/basic-elements/basic-elements.ts",
    "file/src/pages/basic-elements/basic-elements.ts.html",
    "src/pages/basic-elements/basic-elements.ts",
    "file"
  ],
  [
    "src/pages/basic-elements/basic-elements.ts~basicelementspage#constructor",
    "class/src/pages/basic-elements/basic-elements.ts~BasicElementsPage.html#instance-constructor-constructor",
    "src/pages/basic-elements/basic-elements.ts~BasicElementsPage#constructor",
    "method"
  ],
  [
    "src/pages/basic-elements/basic-elements.ts~basicelementspage#createcircles",
    "class/src/pages/basic-elements/basic-elements.ts~BasicElementsPage.html#instance-method-createCircles",
    "src/pages/basic-elements/basic-elements.ts~BasicElementsPage#createCircles",
    "method"
  ],
  [
    "src/pages/basic-elements/basic-elements.ts~basicelementspage#createcoordinatecircles",
    "class/src/pages/basic-elements/basic-elements.ts~BasicElementsPage.html#instance-method-createCoordinateCircles",
    "src/pages/basic-elements/basic-elements.ts~BasicElementsPage#createCoordinateCircles",
    "method"
  ],
  [
    "src/pages/basic-elements/basic-elements.ts~basicelementspage#ionviewdidload",
    "class/src/pages/basic-elements/basic-elements.ts~BasicElementsPage.html#instance-method-ionViewDidLoad",
    "src/pages/basic-elements/basic-elements.ts~BasicElementsPage#ionViewDidLoad",
    "method"
  ],
  [
    "src/pages/basic-shapes/basic-shapes.ts",
    "file/src/pages/basic-shapes/basic-shapes.ts.html",
    "src/pages/basic-shapes/basic-shapes.ts",
    "file"
  ],
  [
    "src/pages/basic-shapes/basic-shapes.ts~basicshapespage#constructor",
    "class/src/pages/basic-shapes/basic-shapes.ts~BasicShapesPage.html#instance-constructor-constructor",
    "src/pages/basic-shapes/basic-shapes.ts~BasicShapesPage#constructor",
    "method"
  ],
  [
    "src/pages/basic-shapes/basic-shapes.ts~basicshapespage#createcircles",
    "class/src/pages/basic-shapes/basic-shapes.ts~BasicShapesPage.html#instance-method-createCircles",
    "src/pages/basic-shapes/basic-shapes.ts~BasicShapesPage#createCircles",
    "method"
  ],
  [
    "src/pages/basic-shapes/basic-shapes.ts~basicshapespage#createellipses",
    "class/src/pages/basic-shapes/basic-shapes.ts~BasicShapesPage.html#instance-method-createEllipses",
    "src/pages/basic-shapes/basic-shapes.ts~BasicShapesPage#createEllipses",
    "method"
  ],
  [
    "src/pages/basic-shapes/basic-shapes.ts~basicshapespage#createlines",
    "class/src/pages/basic-shapes/basic-shapes.ts~BasicShapesPage.html#instance-method-createLines",
    "src/pages/basic-shapes/basic-shapes.ts~BasicShapesPage#createLines",
    "method"
  ],
  [
    "src/pages/basic-shapes/basic-shapes.ts~basicshapespage#createrectangles",
    "class/src/pages/basic-shapes/basic-shapes.ts~BasicShapesPage.html#instance-method-createRectangles",
    "src/pages/basic-shapes/basic-shapes.ts~BasicShapesPage#createRectangles",
    "method"
  ],
  [
    "src/pages/basic-shapes/basic-shapes.ts~basicshapespage#ionviewdidload",
    "class/src/pages/basic-shapes/basic-shapes.ts~BasicShapesPage.html#instance-method-ionViewDidLoad",
    "src/pages/basic-shapes/basic-shapes.ts~BasicShapesPage#ionViewDidLoad",
    "method"
  ],
  [
    "src/pages/dynamic-svg-coord/dynamic-svg-coord.ts",
    "file/src/pages/dynamic-svg-coord/dynamic-svg-coord.ts.html",
    "src/pages/dynamic-svg-coord/dynamic-svg-coord.ts",
    "file"
  ],
  [
    "src/pages/dynamic-svg-coord/dynamic-svg-coord.ts~dynamicsvgcoordpage#constructor",
    "class/src/pages/dynamic-svg-coord/dynamic-svg-coord.ts~DynamicSvgCoordPage.html#instance-constructor-constructor",
    "src/pages/dynamic-svg-coord/dynamic-svg-coord.ts~DynamicSvgCoordPage#constructor",
    "method"
  ],
  [
    "src/pages/dynamic-svg-coord/dynamic-svg-coord.ts~dynamicsvgcoordpage#createdynamicsvg",
    "class/src/pages/dynamic-svg-coord/dynamic-svg-coord.ts~DynamicSvgCoordPage.html#instance-method-createDynamicSvg",
    "src/pages/dynamic-svg-coord/dynamic-svg-coord.ts~DynamicSvgCoordPage#createDynamicSvg",
    "method"
  ],
  [
    "src/pages/dynamic-svg-coord/dynamic-svg-coord.ts~dynamicsvgcoordpage#getmaxsvg",
    "class/src/pages/dynamic-svg-coord/dynamic-svg-coord.ts~DynamicSvgCoordPage.html#instance-method-getMaxSVG",
    "src/pages/dynamic-svg-coord/dynamic-svg-coord.ts~DynamicSvgCoordPage#getMaxSVG",
    "method"
  ],
  [
    "src/pages/dynamic-svg-coord/dynamic-svg-coord.ts~dynamicsvgcoordpage#ionviewdidload",
    "class/src/pages/dynamic-svg-coord/dynamic-svg-coord.ts~DynamicSvgCoordPage.html#instance-method-ionViewDidLoad",
    "src/pages/dynamic-svg-coord/dynamic-svg-coord.ts~DynamicSvgCoordPage#ionViewDidLoad",
    "method"
  ],
  [
    "src/pages/group-element-d3/group-element-d3.ts",
    "file/src/pages/group-element-d3/group-element-d3.ts.html",
    "src/pages/group-element-d3/group-element-d3.ts",
    "file"
  ],
  [
    "src/pages/group-element-d3/group-element-d3.ts~groupelementd3page#constructor",
    "class/src/pages/group-element-d3/group-element-d3.ts~GroupElementD3Page.html#instance-constructor-constructor",
    "src/pages/group-element-d3/group-element-d3.ts~GroupElementD3Page#constructor",
    "method"
  ],
  [
    "src/pages/group-element-d3/group-element-d3.ts~groupelementd3page#createsvg",
    "class/src/pages/group-element-d3/group-element-d3.ts~GroupElementD3Page.html#instance-method-createSVG",
    "src/pages/group-element-d3/group-element-d3.ts~GroupElementD3Page#createSVG",
    "method"
  ],
  [
    "src/pages/group-element-d3/group-element-d3.ts~groupelementd3page#elementref",
    "class/src/pages/group-element-d3/group-element-d3.ts~GroupElementD3Page.html#instance-member-elementRef",
    "src/pages/group-element-d3/group-element-d3.ts~GroupElementD3Page#elementRef",
    "member"
  ],
  [
    "src/pages/group-element-d3/group-element-d3.ts~groupelementd3page#ionviewdidload",
    "class/src/pages/group-element-d3/group-element-d3.ts~GroupElementD3Page.html#instance-method-ionViewDidLoad",
    "src/pages/group-element-d3/group-element-d3.ts~GroupElementD3Page#ionViewDidLoad",
    "method"
  ],
  [
    "src/pages/group-element/group-element.ts",
    "file/src/pages/group-element/group-element.ts.html",
    "src/pages/group-element/group-element.ts",
    "file"
  ],
  [
    "src/pages/group-element/group-element.ts~groupelementpage#constructor",
    "class/src/pages/group-element/group-element.ts~GroupElementPage.html#instance-constructor-constructor",
    "src/pages/group-element/group-element.ts~GroupElementPage#constructor",
    "method"
  ],
  [
    "src/pages/group-element/group-element.ts~groupelementpage#ionviewdidload",
    "class/src/pages/group-element/group-element.ts~GroupElementPage.html#instance-method-ionViewDidLoad",
    "src/pages/group-element/group-element.ts~GroupElementPage#ionViewDidLoad",
    "method"
  ],
  [
    "src/pages/home/home.ts",
    "file/src/pages/home/home.ts.html",
    "src/pages/home/home.ts",
    "file"
  ],
  [
    "src/pages/home/home.ts~homepage#constructor",
    "class/src/pages/home/home.ts~HomePage.html#instance-constructor-constructor",
    "src/pages/home/home.ts~HomePage#constructor",
    "method"
  ],
  [
    "src/pages/home/home.ts~homepage#ionviewdidload",
    "class/src/pages/home/home.ts~HomePage.html#instance-method-ionViewDidLoad",
    "src/pages/home/home.ts~HomePage#ionViewDidLoad",
    "method"
  ],
  [
    "src/pages/home/home.ts~homepage#navctrl",
    "class/src/pages/home/home.ts~HomePage.html#instance-member-navCtrl",
    "src/pages/home/home.ts~HomePage#navCtrl",
    "member"
  ],
  [
    "src/pages/index.ts",
    "file/src/pages/index.ts.html",
    "src/pages/index.ts",
    "file"
  ],
  [
    "src/pages/installation/installation.ts",
    "file/src/pages/installation/installation.ts.html",
    "src/pages/installation/installation.ts",
    "file"
  ],
  [
    "src/pages/installation/installation.ts~installationpage#constructor",
    "class/src/pages/installation/installation.ts~InstallationPage.html#instance-constructor-constructor",
    "src/pages/installation/installation.ts~InstallationPage#constructor",
    "method"
  ],
  [
    "src/pages/installation/installation.ts~installationpage#ionviewdidload",
    "class/src/pages/installation/installation.ts~InstallationPage.html#instance-method-ionViewDidLoad",
    "src/pages/installation/installation.ts~InstallationPage#ionViewDidLoad",
    "method"
  ],
  [
    "src/pages/installation/installation.ts~installationpage#navctrl",
    "class/src/pages/installation/installation.ts~InstallationPage.html#instance-member-navCtrl",
    "src/pages/installation/installation.ts~InstallationPage#navCtrl",
    "member"
  ],
  [
    "src/pages/installation/installation.ts~installationpage#navparams",
    "class/src/pages/installation/installation.ts~InstallationPage.html#instance-member-navParams",
    "src/pages/installation/installation.ts~InstallationPage#navParams",
    "member"
  ],
  [
    "src/pages/paths-svg/paths-svg.ts",
    "file/src/pages/paths-svg/paths-svg.ts.html",
    "src/pages/paths-svg/paths-svg.ts",
    "file"
  ],
  [
    "src/pages/paths-svg/paths-svg.ts~pathssvgpage#constructor",
    "class/src/pages/paths-svg/paths-svg.ts~PathsSvgPage.html#instance-constructor-constructor",
    "src/pages/paths-svg/paths-svg.ts~PathsSvgPage#constructor",
    "method"
  ],
  [
    "src/pages/paths-svg/paths-svg.ts~pathssvgpage#createsvgpathslines",
    "class/src/pages/paths-svg/paths-svg.ts~PathsSvgPage.html#instance-method-createSvgPathsLines",
    "src/pages/paths-svg/paths-svg.ts~PathsSvgPage#createSvgPathsLines",
    "method"
  ],
  [
    "src/pages/paths-svg/paths-svg.ts~pathssvgpage#interpolationselected",
    "class/src/pages/paths-svg/paths-svg.ts~PathsSvgPage.html#instance-member-interpolationSelected",
    "src/pages/paths-svg/paths-svg.ts~PathsSvgPage#interpolationSelected",
    "member"
  ],
  [
    "src/pages/paths-svg/paths-svg.ts~pathssvgpage#interpolations",
    "class/src/pages/paths-svg/paths-svg.ts~PathsSvgPage.html#instance-member-interpolations",
    "src/pages/paths-svg/paths-svg.ts~PathsSvgPage#interpolations",
    "member"
  ],
  [
    "src/pages/paths-svg/paths-svg.ts~pathssvgpage#interpolationsselectlist",
    "class/src/pages/paths-svg/paths-svg.ts~PathsSvgPage.html#instance-member-interpolationsSelectList",
    "src/pages/paths-svg/paths-svg.ts~PathsSvgPage#interpolationsSelectList",
    "member"
  ],
  [
    "src/pages/paths-svg/paths-svg.ts~pathssvgpage#ionviewdidload",
    "class/src/pages/paths-svg/paths-svg.ts~PathsSvgPage.html#instance-method-ionViewDidLoad",
    "src/pages/paths-svg/paths-svg.ts~PathsSvgPage#ionViewDidLoad",
    "method"
  ],
  [
    "src/pages/scales/scales.ts",
    "file/src/pages/scales/scales.ts.html",
    "src/pages/scales/scales.ts",
    "file"
  ],
  [
    "src/pages/scales/scales.ts~scalespage#constructor",
    "class/src/pages/scales/scales.ts~ScalesPage.html#instance-constructor-constructor",
    "src/pages/scales/scales.ts~ScalesPage#constructor",
    "method"
  ],
  [
    "src/pages/scales/scales.ts~scalespage#createscales",
    "class/src/pages/scales/scales.ts~ScalesPage.html#instance-method-createScales",
    "src/pages/scales/scales.ts~ScalesPage#createScales",
    "method"
  ],
  [
    "src/pages/scales/scales.ts~scalespage#initialdatatoscale",
    "class/src/pages/scales/scales.ts~ScalesPage.html#instance-member-initialDataToScale",
    "src/pages/scales/scales.ts~ScalesPage#initialDataToScale",
    "member"
  ],
  [
    "src/pages/scales/scales.ts~scalespage#ionviewdidload",
    "class/src/pages/scales/scales.ts~ScalesPage.html#instance-method-ionViewDidLoad",
    "src/pages/scales/scales.ts~ScalesPage#ionViewDidLoad",
    "method"
  ],
  [
    "src/pages/scales/scales.ts~scalespage#ispushed",
    "class/src/pages/scales/scales.ts~ScalesPage.html#instance-member-isPushed",
    "src/pages/scales/scales.ts~ScalesPage#isPushed",
    "member"
  ],
  [
    "src/pages/scales/scales.ts~scalespage#navctrl",
    "class/src/pages/scales/scales.ts~ScalesPage.html#instance-member-navCtrl",
    "src/pages/scales/scales.ts~ScalesPage#navCtrl",
    "member"
  ],
  [
    "src/pages/scales/scales.ts~scalespage#navparams",
    "class/src/pages/scales/scales.ts~ScalesPage.html#instance-member-navParams",
    "src/pages/scales/scales.ts~ScalesPage#navParams",
    "member"
  ],
  [
    "src/pages/scales/scales.ts~scalespage#scaleddata",
    "class/src/pages/scales/scales.ts~ScalesPage.html#instance-member-scaledData",
    "src/pages/scales/scales.ts~ScalesPage#scaledData",
    "member"
  ],
  [
    "src/pages/text-element/text-element.ts",
    "file/src/pages/text-element/text-element.ts.html",
    "src/pages/text-element/text-element.ts",
    "file"
  ],
  [
    "src/pages/text-element/text-element.ts~textelementpage#constructor",
    "class/src/pages/text-element/text-element.ts~TextElementPage.html#instance-constructor-constructor",
    "src/pages/text-element/text-element.ts~TextElementPage#constructor",
    "method"
  ],
  [
    "src/pages/text-element/text-element.ts~textelementpage#createsvg",
    "class/src/pages/text-element/text-element.ts~TextElementPage.html#instance-method-createSVG",
    "src/pages/text-element/text-element.ts~TextElementPage#createSVG",
    "method"
  ],
  [
    "src/pages/text-element/text-element.ts~textelementpage#ionviewdidload",
    "class/src/pages/text-element/text-element.ts~TextElementPage.html#instance-method-ionViewDidLoad",
    "src/pages/text-element/text-element.ts~TextElementPage#ionViewDidLoad",
    "method"
  ],
  [
    "src/pages/text-element/text-element.ts~textelementpage#navctrl",
    "class/src/pages/text-element/text-element.ts~TextElementPage.html#instance-member-navCtrl",
    "src/pages/text-element/text-element.ts~TextElementPage#navCtrl",
    "member"
  ],
  [
    "src/pages/text-element/text-element.ts~textelementpage#navparams",
    "class/src/pages/text-element/text-element.ts~TextElementPage.html#instance-member-navParams",
    "src/pages/text-element/text-element.ts~TextElementPage#navParams",
    "member"
  ],
  [
    "src/service-worker.js",
    "file/src/service-worker.js.html",
    "src/service-worker.js",
    "file"
  ]
]